# Added PETSc include and lib paths
PETSC_DIR = /opt/ohpc/pub/libs/gnu7/mvapich2/petsc/3.1-p8
PETSC_ARCH = linux-gnu-c-opt

CFLAGS += -I$(PETSC_DIR)/include -I$(PETSC_DIR)/$(PETSC_ARCH)/include
LDFLAGS += -L$(PETSC_DIR)/$(PETSC_ARCH)/lib -L/opt/ohpc/pub/libs/gnu7/mvapich2/petsc/3.1-p8/lib -lpetsc

# HYPRE paths
HYPRE_DIR = /opt/ohpc/pub/libs/gnu7/mvapich2/hypre/2.14.0
CFLAGS += -I$(HYPRE_DIR)/include
LDFLAGS += -L$(HYPRE_DIR)/lib -L/opt/ohpc/pub/libs/gnu7/mvapich2/hypre/2.14.0/lib -lHYPRE

TEC360HOME=$(HOME)/lib/TECIO/360_2009_R2
TECINC  = $(TEC360HOME)/include/
TECLIB  = $(TEC360HOME)/lib/

CC      = mpicxx

EXEC = VFS-Geophysics-3.1-mhk-GenInflow-parallel


LIBFLAG =       -lpthread -lrt -ldl -lstdc++ -L/opt/ohpc/pub/libs/gnu7/mvapich2/fftw/3.3.7/lib -lfftw3 \
                -L/opt/ohpc/pub/libs/gnu7/mvapich2/petsc/3.1-p8/lib -lpetsc -L/opt/ohpc/pub/libs/gnu7/mvapich2/hypre/2.14.0/lib -lHYPRE  -lgfortran -L/opt/ohpc/pub/libs/gnu7/openblas/0.2.20/lib -lopenblas

SOURCEC =       GenerateInflow-parallel.c\

OBJSC   = $(SOURCEC:%.c=%.o)

CPPFLAGS =	-DNDEBUG        -DTECIO=1 -O3 -I/opt/ohpc/pub/libs/gnu7/mvapich2/fftw/3.3.7/include -I$(TECINC)

test:   $(OBJSC)
	$(CC) -o $(EXEC) $(OBJSC) $(CPPFLAGS)  $(LIBFLAG)


VFS-Geophysics-3.1-mhk:   $(OBJSC)
	$(CC) -o VFS-Geophysics-3.1-mhk $(OBJSC) $(CPPFLAGS) $(LIBDIR) $(LIBFLAG)

data-3.1: data.o
	$(CC) -o data-3.1 data.o $(CPPFLAGS) $(LIBFLAG) $(TECLIB)/tecio64.a

data-small-3.1: data-small.o
	$(CC) -o data-small-3.1 data-small.o $(CPPFLAGS) $(LIBDIR) $(LIBFLAG) tecio64.a

data05: data05.o
	$(CC) -o data05 data05.o $(CPPFLAGS) $(LIBDIR) $(LIBFLAG)

itfcsearch: itfcsearch.o
	$(CC) -o itfcsearch itfcsearch.o $(CPPFLAGS) $(LIBDIR) $(LIBFLAG)

shear: shear.o

##data1: data1.o
##$(CC) -o data1 data1.o $(CPPFLAGS) $(LIBDIR) $(LIBFLAG) tecio64.a

hill: hill.o
	$(CC) -o hill hill.o $(CPPFLAGS) $(LIBDIR) $(LIBFLAG)

#xyz: xyz2Plot3d.o
#      $(CC) -o xyz xyz2Plot3d.o $(CPPFLAGS) $(LIBDIR) $(LIBFLAG)

clean:
	-rm -f *.o
	-rm -f data-3.1
	-rm -f VFS-Geophysics-3.1-p8

turbine: TurbineLoc.o
	$(CC) -o TurbineLoc TurbineLoc.o $(CPPFLAGS) $(LIBDIR) $(LIBFLAG)
terrain: terrain.o
	$(CC) -o terrain terrain.o $(CPPFLAGS) $(LIBDIR) $(LIBFLAG)
Tec2UCD: OSLTec2UCD.o
	$(CC) -o Tec2UCD OSLTec2UCD.o $(CPPFLAGS) $(LIBDIR) $(LIBFLAG)

#GenerateInflow: GenerateInflow__.o
#       $(CC) -o GenerateInflow GenerateInflow__.o $(CPPFLAGS) $(LIBDIR) $(LIBFLAG) tecio64.a

#ReadKevin_3dhilldat: ReadKevin_3dhilldat.o
#       $(CC) -o ReadKevin_3dhilldat ReadKevin_3dhilldat.o $(CPPFLAGS) $(LIBDIR) $(LIBFLAG) tecio64.a

#UCD2Plot3d: ucd2Plot3d_OSL.o
#       $(CC) -o UCD2Plot3d ucd2Plot3d_OSL.o $(CPPFLAGS) $(LIBDIR) $(LIBFLAG) tecio64.a

#GenInflow2: GenInflow2.o
#       $(CC) -o GenInflow2 GenInflow2.o $(CPPFLAGS) $(LIBDIR) $(LIBFLAG) tecio64.a


#SPAnal: SPAnal.o
#       $(CC) -o SPAnal SPAnal.o $(CPPFLAGS) $(LIBDIR) $(LIBFLAG) tecio64.a

#GenInflow3: GenInflow3.o
#       $(CC) -o GenInflow3 GenInflow3.o $(CPPFLAGS) $(LIBDIR) $(LIBFLAG) tecio64.a

LDFLAGS += -L$(PETSC_DIR)/lib -L/opt/ohpc/pub/libs/gnu7/mvapich2/petsc/3.1-p8/lib -lpetsc
LDFLAGS += -L$(HYPRE_DIR)/lib -L/opt/ohpc/pub/libs/gnu7/mvapich2/hypre/2.14.0/lib -lHYPRE
LDFLAGS += -llapack -lblas
